name: "Build and Push Image"
on: push
jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Image Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_SERVER }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Publish
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKER_SERVER }}/${{ secrets.DOCKER_SERVER }}/serve:latest
